Shop = Shop or {}
Shop.defaultPrice = 2
Shop.defaultPriceBroken = 1
Shop.SellisBlacklist = false

Shop.SellisWhitelist = SandboxVars.EdenShops.CanSellAnything or true

Shop.Sell = {
	["AuthenticZClothing.AuthenticTagillaSledgehammer"] = { price = 500 },
	["AuthenticZClothing.Necklace_B"] = { price = 30 },
	["AuthenticZClothing.Necklace_GoldCrucifix"] = { price = 30 },
	["Base.223Box"] = { price = 25 },
	["Base.308Box"] = { price = 25 },
	["Base.556Box"] = { price = 25 },
	["Base.762x51Box"] = { price = 25 },
	["Base.Bass"] = { price = 50 },
	["Base.BellyButton_DangleGold"] = { price = 10 },
	["Base.BellyButton_DangleGoldRuby"] = { price = 15 },
	["Base.BellyButton_DangleSilver"] = { price = 10 },
	["Base.BellyButton_DangleSilverDiamond"] = { price = 20 },
	["Base.BellyButton_RingGold"] = { price = 10 },
	["Base.BellyButton_RingGoldDiamond"] = { price = 20 },
	["Base.BellyButton_RingGoldRuby"] = { price = 15 },
	["Base.BellyButton_RingSilver"] = { price = 10 },
	["Base.BellyButton_RingSilverAmethyst"] = { price = 15 },
	["Base.BellyButton_RingSilverDiamond"] = { price = 20 },
	["Base.BellyButton_RingSilverRuby"] = { price = 15 },
	["Base.BellyButton_StudGold"] = { price = 10 },
	["Base.BellyButton_StudGoldDiamond"] = { price = 20 },
	["Base.BellyButton_StudSilver"] = { price = 10 },
	["Base.BellyButton_StudSilverDiamond"] = { price = 20 },
	["Base.Bracelet_BangleLeftGold"] = { price = 25 },
	["Base.Bracelet_BangleLeftSilver"] = { price = 25 },
	["Base.Bracelet_BangleRightGold"] = { price = 25 },
	["Base.Bracelet_BangleRightSilver"] = { price = 25 },
	["Base.Bracelet_ChainLeftGold"] = { price = 25 },
	["Base.Bracelet_ChainLeftSilver"] = { price = 25 },
	["Base.Bracelet_ChainRightGold"] = { price = 25 },
	["Base.Bracelet_ChainRightSilver"] = { price = 25 },
	["Base.Bracelet_LeftFriendshipTINT"] = { price = 15 },
	["Base.Bracelet_RightFriendshipTINT"] = { price = 15 },
	["Base.Broccoli"] = { price = 5 },
	["Base.Bullets22Box"] = { price = 25 },
	["Base.Bullets3006Box"] = { price = 25 },
	["Base.Bullets38Box"] = { price = 25 },
	["Base.Bullets44Box"] = { price = 25 },
	["Base.Bullets45Box"] = { price = 25 },
	["Base.Bullets9mmBox"] = { price = 25 },
	["Base.Cabbage"] = { price = 5 },
	["Base.Candycane"] = { price = 5},
	["Base.CandyPackage"] = { price = 5},
	["Base.CannedBacon"] = { price = 5},
	["Base.CannedBolognese"] = { price = 5},
	["Base.CannedBread"] = { price = 5},
	["Base.CannedCarrots2"] = { price = 5},
	["Base.CannedChili"] = { price = 5},
	["Base.CannedCorn"] = { price = 5},
	["Base.CannedCornedBeef"] = { price = 5},
	["Base.CannedFruit_Beverage"] = { price = 5},
	["Base.CannedFruitCocktail"] = { price = 5},
	["Base.CannedMilk"] = { price = 5},
	["Base.CannedMushroomSoup"] = { price = 5},
	["Base.CannedPeaches"] = { price = 5},
	["Base.CannedPeas"] = { price = 5},
	["Base.CannedPineapple"] = { price = 5},
	["Base.CannedPotato2"] = { price = 5},
	["Base.CannedSardines"] = { price = 5},
	["Base.CannedSausages"] = { price = 5},
	["Base.CannedTomato2"] = { price = 5},
	["Base.Carrot"] = { price = 5 },
	["Base.Catfish"] = { price = 50 },
	["Base.Cereal"] = { price = 5},
	["Base.Crappie"] = { price = 50 },
	["Base.Crayfish"] = { price = 50 },
	["Base.CreditCard"] = { price = 50 },
	["Base.Crisps"] = { price = 5},
	["Base.Crisps2"] = { price = 5},
	["Base.Crisps3"] = { price = 5},
	["Base.Crisps4"] = { price = 5},
	["Base.Dogfood"] = { price = 5},
	["Base.DriedBlackBeans"] = { price = 5},
	["Base.DriedChickpeas"] = { price = 5},
	["Base.DriedKidneyBeans"] = { price = 5},
	["Base.DriedLentils"] = { price = 5},
	["Base.DriedSplitPeas"] = { price = 5},
	["Base.DriedWhiteBeans"] = { price = 5},
	["Base.Earring_Dangly_Diamond"] = { price = 20 },
	["Base.Earring_Dangly_Emerald"] = { price = 15 },
	["Base.Earring_Dangly_Pearl"] = { price = 20 },
	["Base.Earring_Dangly_Ruby"] = { price = 15 },
	["Base.Earring_Dangly_Sapphire"] = { price = 15 },
	["Base.Earring_LoopLrg_Gold"] = { price = 10 },
	["Base.Earring_LoopLrg_Silver"] = { price = 10 },
	["Base.Earring_LoopMed_Gold"] = { price = 10 },
	["Base.Earring_LoopMed_Silver"] = { price = 10 },
	["Base.Earring_LoopSmall_Gold_Both"] = { price = 10 },
	["Base.Earring_LoopSmall_Gold_Top"] = { price = 10 },
	["Base.Earring_LoopSmall_Silver_Both"] = { price = 10 },
	["Base.Earring_LoopSmall_Silver_Top"] = { price = 10 },
	["Base.Earring_Pearl"] = { price = 15 },
	["Base.Earring_Stone_Emerald"] = { price = 15 },
	["Base.Earring_Stone_Ruby"] = { price = 15 },
	["Base.Earring_Stone_Sapphire"] = { price = 15 },
	["Base.Earring_Stud_Gold"] = { price = 10 },
	["Base.Earring_Stud_Silver"] = { price = 10 },
	["Base.EXO_Suit_ON"] = { price = 100 },
        ["Base.Locket"] = { price = 5},
	["Base.Macandcheese"] = { price = 5},
	["Base.Marinara"] = { price = 5},
	["Base.MetalBar"] = { price = 5 },
	["Base.MetalPipe"] = { price = 5 },
	["Base.Necklace_Choker_Amber"] = { price = 20 },
	["Base.Necklace_Choker_Diamond"] = { price = 30 },
	["Base.Necklace_Choker_Sapphire"] = { price = 20 },
	["Base.Necklace_Choker"] = { price = 10 },
	["Base.Necklace_Crucifix"] = { price = 20 },
	["Base.Necklace_DogTag"] = { price = 15 },
	["Base.Necklace_Gold"] = { price = 10 },
	["Base.Necklace_GoldDiamond"] = { price = 30 },
	["Base.Necklace_GoldRuby"] = { price = 20 },
	["Base.Necklace_Pearl"] = { price = 30 },
	["Base.Necklace_Silver"] = { price = 10 },
	["Base.Necklace_SilverCrucifix"] = { price = 20 },
	["Base.Necklace_SilverDiamond"] = { price = 30 },
	["Base.Necklace_SilverSapphire"] = { price = 20 },
	["Base.Necklace_YingYang"] = { price = 20 },
	["Base.NecklaceLong_Amber"] = { price = 20 },
	["Base.NecklaceLong_Gold"] = { price = 10 },
	["Base.NecklaceLong_GoldDiamond"] = { price = 30 },
	["Base.NecklaceLong_Silver"] = { price = 10 },
	["Base.NecklaceLong_SilverDiamond"] = { price = 30 },
	["Base.NecklaceLong_SilverEmerald"] = { price = 20 },
	["Base.NecklaceLong_SilverSapphire"] = { price = 20 },
	["Base.NoseRing_Gold"] = { price = 10 },
	["Base.NoseRing_Silver"] = { price = 10 },
	["Base.NoseStud_Gold"] = { price = 10 },
	["Base.NoseStud_Silver"] = { price = 10 },
	["Base.OatsRaw"] = { price = 5},
	["Base.PancakeMix"] = { price = 5},
	["Base.Panfish"] = { price = 50 },
	["Base.Pasta"] = { price = 5},
	["Base.PeanutButter"] = { price = 5},
	["Base.Perch"] = { price = 50 },
	["Base.Pike"] = { price = 50 },
	["Base.Potato"] = { price = 5 },
	["Base.Radish"] = { price = 5 },
	["Base.Rice"] = { price = 5},
	["Base.Ring_Left_MiddleFinger_Gold"] = { price = 10 },
	["Base.Ring_Left_MiddleFinger_GoldDiamond"] = { price = 20 },
	["Base.Ring_Left_MiddleFinger_GoldRuby"] = { price = 15 },
	["Base.Ring_Left_MiddleFinger_Silver"] = { price = 10 },
	["Base.Ring_Left_MiddleFinger_SilverDiamond"] = { price = 20 },
	["Base.Ring_Left_RingFinger_Gold"] = { price = 10 },
	["Base.Ring_Left_RingFinger_GoldDiamond"] = { price = 20 },
	["Base.Ring_Left_RingFinger_GoldRuby"] = { price = 15 },
	["Base.Ring_Left_RingFinger_Silver"] = { price = 10 },
	["Base.Ring_Left_RingFinger_SilverDiamond"] = { price = 20 },
	["Base.Ring_Right_MiddleFinger_Gold"] = { price = 10 },
	["Base.Ring_Right_MiddleFinger_GoldDiamond"] = { price = 20 },
	["Base.Ring_Right_MiddleFinger_GoldRuby"] = { price = 15 },
	["Base.Ring_Right_MiddleFinger_Silver"] = { price = 10 },
	["Base.Ring_Right_MiddleFinger_SilverDiamond"] = { price = 20 },
	["Base.Ring_Right_RingFinger_Gold"] = { price = 10 },
	["Base.Ring_Right_RingFinger_GoldDiamond"] = { price = 20 },
	["Base.Ring_Right_RingFinger_GoldRuby"] = { price = 15 },
	["Base.Ring_Right_RingFinger_Silver"] = { price = 10 },
	["Base.Ring_Right_RingFinger_SilverDiamond"] = { price = 20 },
	["Base.SheetMetal"] = { price = 10 },
	["Base.ShotgunShellsBox"] = { price = 25 },
	["Base.Sledgehammer"] = { price = 50 },
	["Base.Sledgehammer2"] = { price = 50 },
	["Base.SmallSheetMetal"] = { price = 5 },
	["Base.Strawberry"] = { price = 5 },
	["Base.TinnedBeans"] = { price = 5},
	["Base.TinnedSoup"] = { price = 5},
	["Base.Tomato"] = { price = 5 },
	["Base.Trout"] = { price = 50 },
	["Base.TunaTin"] = { price = 5},
	["Base.WeddingRing_Man"] = { price = 10 },
	["Base.WeddingRing_Woman"] = { price = 10 },
	["Base.WristWatch_Left_ClassicBlack"] = { price = 15 },
	["Base.WristWatch_Left_ClassicBrown"] = { price = 15 },
	["Base.WristWatch_Left_ClassicGold"] = { price = 30 },
	["Base.WristWatch_Left_ClassicMilitary"] = { price = 20 },
	["Base.WristWatch_Left_DigitalBlack"] = { price = 15 },
	["Base.WristWatch_Left_DigitalDress"] = { price = 20 },
	["Base.WristWatch_Left_DigitalRed"] = { price = 15 },
	["Base.WristWatch_Right_ClassicBlack"] = { price = 15 },
	["Base.WristWatch_Right_ClassicBrown"] = { price = 15 },
	["Base.WristWatch_Right_ClassicGold"] = { price = 30 },
	["Base.WristWatch_Right_ClassicMilitary"] = { price = 20 },
	["Base.WristWatch_Right_DigitalBlack"] = { price = 15 },
	["Base.WristWatch_Right_DigitalDress"] = { price = 20 },
	["Base.WristWatch_Right_DigitalRed"] = { price = 15 },
	["pkmncards.cardbinder_full"] = { price = 10000 },
        ["MoreSmokes.NorthernLightsZipLockBag"] = { price = 100 },
        ["MoreSmokes.PurpleHazeZipLockBag"] = { price = 100 },
        ["MoreSmokes.SourDieselZipLockBag"] = { price = 100 },
}